name: Build Elite IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Project
        run: |
          brew install xcodegen
          xcodegen generate

      - name: Build
        run: |
          # العثور على اسم الـ Scheme تلقائياً
          scheme=$(xcodebuild -list | grep "Scheme:" | head -n 1 | awk '{print $2}')
          xcodebuild -project EliteIPA.xcodeproj -scheme "$scheme" -configuration Release build
