name: Build Elite IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Project
        run: |
          curl -sL https://github.com/yonaskolb/XcodeGen/releases/latest/download/xcodegen.zip -o xcodegen.zip
          unzip xcodegen.zip
          chmod +x xcodegen
          ./xcodegen generate

      - name: Build
        run: xcodebuild -project EliteIPA.xcodeproj -scheme EliteIPA -configuration Release build
